# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - develop

resources:
  - repo: self

variables:
  tag: dev
  containerRegistry: cvuintell-docker-hub
  HELM_VERSION: "3.0.2"
  devK8sService: codwer-reru-azure-k8s

stages:
  - stage: Build
    displayName: Building Images and  publishing images
    jobs:
      - job: Build
        displayName: Build images
        pool:
          name: "Default"

        steps:
          - task: PowerShell@2
            displayName: Calculating changed projects
            inputs:
              targetType: "inline"
              script: |
                $files=$(git diff HEAD HEAD~ --name-only)
                $temp=$files -split ' '
                $count=$temp.Length
                echo "Total changed $count files"
                For ($i=0; $i -lt $temp.Length; $i++)
                {
                  $name=$temp[$i]
                  echo "this is $name file"
                  
                  if ($name -like "src/Microservices/CODWER.RERU.Identity/CODWER.RERU.IdentityMigrator.Console/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildIdentityMigrator]True"
                    }

                  if ($name -like "src/Microservices/CODWER.RERU.Identity/CODWER.RERU.Identity.Web/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildIdentityNew]True"
                    }

                  if ($name -like "src/Microservices/CODWER.RERU.Gateway/CODWER.RERU.Gateway.Public/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildPublicGateway]True"
                    }

                  if ($name -like "src/Microservices/CODWER.RERU.Gateway/CODWER.RERU.Gateway.Internal/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildInternalGateway]True"
                    }

                  if ($name -like "src/Microservices/CODWER.RERU.Core/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildCore]True"
                    }

                  if ($name -like "src/Microservices/CODWER.RERU.Personal/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildPersonal]True"
                    }                

                  if ($name -like "src/Microservices/CODWER.RERU.Evaluation/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildEvaluation]True"
                    }


                  if ($name -like "src/Front-End/reru/projects/core/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildCoreFE]True"
                    }

                  if ($name -like "src/Front-End/reru/projects/personal/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildPersonalFE]True"
                    }

                  if ($name -like "src/Front-End/reru/projects/evaluation/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildEvaluationFE]True"
                    }

                  if ($name -like "src/Front-End/reru/projects/reru-shared/*")
                    {
                      Write-Host "##vso[task.setvariable variable=BuildEvaluationFE]True"
                      Write-Host "##vso[task.setvariable variable=BuildPersonalFE]True"
                      Write-Host "##vso[task.setvariable variable=BuildCoreFe]True"
                    }
                }

          - task: Docker@2
            displayName: Building Public Gateway image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-public-gateway"
              dockerfile: "docker-files/Dockerfile-RERU-PublicGateway"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildPublicGateway'], 'True'))

          - task: Docker@2
            displayName: "Docker push"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-public-gateway"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildPublicGateway'], 'True'))


          - task: Docker@2
            displayName: Building Internal Gateway image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-internal-gateway"
              dockerfile: "docker-files/Dockerfile-RERU-InternalGateway"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildInternalGateway'], 'True'))

          - task: Docker@2
            displayName: "Docker push"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-internal-gateway"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildInternalGateway'], 'True'))


          - task: Docker@2
            displayName: Building Identity New image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-identity-new"
              dockerfile: "docker-files/Dockerfile-RERU-Identity"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildIdentityNew'], 'True'))

          - task: Docker@2
            displayName: "Docker push Identity Image"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-identity-new"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildIdentityNew'], 'True'))


          - task: Docker@2
            displayName: Building Identity Migrator back end image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-identity-migrator"
              dockerfile: "docker-files/Dockerfile-RERU-IdentityMigrator"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildIdentityMigrator'], 'True'))

          - task: Docker@2
            displayName: "Push Identity Migrator back end image"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-identity-migrator"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildIdentityMigrator'], 'True'))


          - task: Docker@2
            displayName: Building Core front end image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-core-fe"
              dockerfile: "docker-files/Dockerfile-RERU-Core-FE"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildCoreFE'], 'True'))

          - task: Docker@2
            displayName: "Docker push Core front end image"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-core-fe"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildCoreFE'], 'True'))


          - task: Docker@2
            displayName: Building Core image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-core"
              dockerfile: "docker-files/Dockerfile-RERU-Core"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildCore'], 'True'))

          - task: Docker@2
            displayName: "Docker push Core Image"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-core"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildCore'], 'True'))


          - task: Docker@2
            displayName: Building Personal front end  image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-personal-fe"
              dockerfile: "docker-files/Dockerfile-RERU-Personal-FE"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildPersonalFE'], 'True'))

          - task: Docker@2
            displayName: "Docker push Personal front end image"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-personal-fe"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildPersonalFE'], 'True'))


          - task: Docker@2
            displayName: Building Personal back end image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-personal"
              dockerfile: "docker-files/Dockerfile-RERU-Personal"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildPersonal'], 'True'))

          - task: Docker@2
            displayName: "Docker push Personal back end image"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-personal"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildPersonal'], 'True'))


          - task: Docker@2
            displayName: Building Evaluation front end  image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-evaluation-fe"
              dockerfile: "docker-files/Dockerfile-RERU-Evaluation-FE"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildEvaluationFE'], 'True'))

          - task: Docker@2
            displayName: "Docker push Evaluation front end image"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-evaluation-fe"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildEvaluationFE'], 'True'))


          - task: Docker@2
            displayName: Building Evaluation back end image
            inputs:
              command: build
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-evaluation"
              dockerfile: "docker-files/Dockerfile-RERU-Evaluation"
              tags: |
                $(tag)
            condition: and(succeeded(), eq(variables['BuildEvaluation'], 'True'))

          - task: Docker@2
            displayName: "Docker push Evaluation back end image"
            inputs:
              containerRegistry: $(containerRegistry)
              repository: "cvuintell/reru-evaluation"
              command: "push"
              tags: $(tag)
              addPipelineData: false
            condition: and(succeeded(), eq(variables['BuildEvaluation'], 'True'))
            

          - task: CmdLine@2
            displayName: Clean all docker resources
            inputs:
              script: 'docker system prune -a --force' 

  - stage: DeployDev
    displayName: Deploy to DEV
    pool:
      name: "Default"
    variables:
      k8sNamespace: reru
      k8sReleaseName: reru-app-stage
    jobs:
      - deployment: DeployDev
        environment: RERUPlatform-DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  lfs: true
                - task: HelmInstaller@1
                  displayName: Install Helm CLI

                - task: Kubernetes@1
                  displayName: Login to Kubernetes
                  inputs:
                    connectionType: Kubernetes Service Connection
                    kubernetesServiceEndpoint: $(devK8sService)
                    command: login
                - bash: >
                    helm upgrade $(k8sReleaseName) helm/chart/
                    --install 
                    --atomic 
                    --namespace $(k8sNamespace)
                    --recreate-pods 
                    --values helm/values.dev.yaml
                  #  --set-string core.database.connection_string="$(dev_core_connection_string)"

                - task: Kubernetes@1
                  displayName: Logout from Kubernetes
                  inputs:
                    command: logout
