apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVSUNLSWg0TzJJS3RGTzdmYnd3UDc1cW9Kai9Fd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXhNVEF4TlRFM05USXdObG9YRFRNeApNVEF4TXpFM05USXdObG93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3NHBVRSt5cCtYN3RkY0RCM3Z3RVFMRk02Q2xxeE5KWk5HUlIKRjNtUklLRmNWcjl5NW1rRnQ5UG9zRHowMTVTbVJSWTBhR21XK1Yzc0QxWjc3WS80VksxL2x5SS84aTRGQWJjSQptcTdzRmdpaDRNNVp6TkJJcTNYaW1wTHFTbCtDMXY3eC9NNTRVMGZOcFJpdGRQMXcvejlVanhZeWEwWmkrSnp5CklRSEs4bmk4L21CK2ZsRmVTek5yenhjMVJKS1ZvaDZwaFZQbWdzczMyTmNxUUxVRWZGYkl1ditKVUtTM0ViREEKeFB5WWdQNlZYKzVEL3paUWd2Z1Vsc2NmODBnUmp6cDNDWjdkNkk5ZWV5Zlg5Y01LYnBHeWYzd2VhOW42SmR4YQpIVjhhdUVRSWRORzMzNk51dUNGanhSSVRzWUY0SGx3SEIzLzAzTE82Ly82UWs2Y3JYd0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVXVuckZFeVlaNG4wYzVORE5XMUsxVzFDUnl3VXdId1lEVlIwakJCZ3dGb0FVdW5yRkV5WVoKNG4wYzVORE5XMUsxVzFDUnl3VXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBZVNRc2p4NE9oWHMvQUJzM2R0SUVrVG8vN0x6eERWOHBSYkVNMk1WQllEd3Y0VnZzL2RXUFVEYkFRSnBVCjI3U0ZhcG5mclM4c0RadVJ4T2hYS01FT0xCaTlRVlRSaStlRTRNVjJoSEI4RW5WQnd6dXdVQkV3WFNxWi8rTTUKc0hDQUlhdU5QdlRDcHdsSk1tVGlPOWpxTENLNUtkNW1XYlBxdmpvclA5c0sxang4dEZjdWNIeEpibmFraktMKwpLVEhVblFRMnV4RVdjOVJtSXBPQ0p2L1VPRmhDQmZEZytLTkNUZWhqOGRGeElBL3BiRkc1RUpWczlYeGRNRmpMCldTTTNMN2t4aFBuQ083Rk03a3YzVjFRa2N2RngrRnZFNWVMQVJ3bENYVzE3blA2Q3FGeS91cThDVXE2czF6Q0kKSmdIaHNwVHNOMWxvaytMenpFa0o0OGV6WEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://82.77.182.132:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    namespace: reru
    user: admin
  name: codwer-kube
current-context: codwer-kube
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: ZVIxQjI5Y05ScFdRcmxoRUxCbVBEbUQ4Rzk5dy9UbjdscjlyTmZRVUhTTT0K
