FROM node:12.18.3-alpine as npm
WORKDIR /src
COPY . .
WORKDIR "/src/src/Front-End/reru/"

RUN npm install \
    && npm run build erp-shared \
    && npm link "./dist/erp-shared" \
    && npm run build core -- --prod --output-path=/src/src/Front-End/reru/dist/core

FROM nginxinc/nginx-unprivileged
COPY ./docker-settings/nginx/nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html

COPY --from=npm /src/src/Front-End/reru/dist/core/ ./
