# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: "restore"
      projects: "**/CVU.ERP.Infrastructure.csproj"
      feedsToUse: "select"
      vstsFeed: "291e92b7-ee93-4c4e-a5b4-a782100d2421/cd1c0186-4930-4bf3-88cf-330daedb1591"
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/CVU.ERP.Infrastructure.csproj'
      arguments: '-c Release'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: DotNetCoreCLI@2
    inputs:
      command: "pack"
      packagesToPack: "**/CVU.ERP.Infrastructure.csproj"
      configuration: 'Release'
      versioningScheme: "off"
      
  - task: DotNetCoreCLI@2
    inputs:
      command: "push"
      packagesToPush: "**/CVU.ERP.Infrastructure.**.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "291e92b7-ee93-4c4e-a5b4-a782100d2421/cd1c0186-4930-4bf3-88cf-330daedb1591"
      arguments: '-c Release'
      publishPackageMetadata: false