import { Evaluation, EvaluationAcceptModel, EvaluationCounterSignModel } from '../index';

export const parseEvaluation = (data: Evaluation): Evaluation => {
    return {
        id: data.id ? +data.id : undefined,
        subdivisionName: data.subdivisionName,
        evaluatedName: data.evaluatedName,
        dateCompletionGeneralData: data.dateCompletionGeneralData,
        nameSurnameEvaluated: data.nameSurnameEvaluated,
        functionSubdivision: data.functionSubdivision,
        specialOrMilitaryGrade: data.specialOrMilitaryGrade,
        specialOrMilitaryGradeText: data.subdivisionName,
        periodEvaluatedFromTo: data.subdivisionName,
        periodEvaluatedUpTo: data.subdivisionName,
        educationEnum: data.educationEnum,
        professionalTrainingActivities: data.professionalTrainingActivities,
        professionalTrainingActivitiesType: data?.professionalTrainingActivitiesType,
        courseName: data?.courseName,
        periodRunningActivityFromTo: data?.periodRunningActivityFromTo,
        periodRunningActivityUpTo: data?.periodRunningActivityUpTo,
        administrativeActOfStudies: data?.administrativeActOfStudies,
        serviceDuringEvaluationCourse: data?.serviceDuringEvaluationCourse,
        functionEvaluated: data?.functionEvaluated,
        appointmentDate: data?.appointmentDate,
        administrativeActService: data?.administrativeActService,
        partialEvaluationPeriodFromTo: data?.partialEvaluationPeriodFromTo,
        partialEvaluationPeriodUpTo: data?.partialEvaluationPeriodUpTo,
        finalScorePartialEvaluations: data?.finalScorePartialEvaluations,
        qualifierPartialEvaluations: data?.qualifierPartialEvaluations,
        sanctionAppliedEvaluationCourse: data?.sanctionAppliedEvaluationCourse,
        dateSanctionApplication: data?.dateSanctionApplication,
        dateLiftingSanction: data?.dateLiftingSanction,
        qualificationEvaluationObtained2YearsPast: data?.qualificationEvaluationObtained2YearsPast,
        qualificationEvaluationObtainedPreviousYear: data?.qualificationEvaluationObtainedPreviousYear,
        qualificationQuarter1: data?.qualificationQuarter1,
        qualificationQuarter2: data?.qualificationQuarter2,
        qualificationQuarter3: data?.qualificationQuarter3,
        qualificationQuarter4: data?.qualificationQuarter4,
        question1: data?.question1,
        question2: data?.question2,
        question3: data?.question3,
        question4: data?.question4,
        question5: data?.question5,
        question6: data?.question6,
        question7: data?.question7,
        question8: data?.question8,
        question9: data?.question9,
        question10: data?.question10,
        question11: data?.question11,
        question12: data?.question12,
        question13: data?.question13,
        goal1: data.goal1,
        goal2: data.goal2,
        goal3: data.goal3,
        goal4: data.goal4,
        goal5: data.goal5,
        kpI1: data.kpI1,
        kpI2: data.kpI2,
        kpI3: data.kpI3,
        kpI4: data.kpI4,
        kpI5: data.kpI5,
        performanceTerm1: data.performanceTerm1,
        performanceTerm2: data.performanceTerm2,
        performanceTerm3: data.performanceTerm3,
        performanceTerm4: data.performanceTerm4,
        performanceTerm5: data.performanceTerm5,
        score1: data.score1,
        score2: data.score2,
        score3: data.score3,
        score4: data.score4,
        score5: data.score5,
        finalEvaluationQualification: data.score5,
        dateEvaluatiorInterview: data.dateEvaluatiorInterview,
        dateSettingIindividualGoals: data.dateSettingIindividualGoals,
        need1ProfessionalDevelopmentEvaluated: data.need1ProfessionalDevelopmentEvaluated,
        need2ProfessionalDevelopmentEvaluated: data.need2ProfessionalDevelopmentEvaluated,
        commentsEvaluator: data.commentsEvaluator,
    }
}

export const parseEvaluatedModel= (data: EvaluationAcceptModel): EvaluationAcceptModel => {
    return {
        id: +data.id,
        commentsEvaluated: data.commentsEvaluated,
        dateAcceptOrRejectEvaluated: data.dateAcceptOrRejectEvaluated,
        signatureEvaluated: !!data.signatureEvaluated
    }
}

export const parseCounterSignModel = (data: EvaluationCounterSignModel): EvaluationCounterSignModel => {
    return {
        id: +data.id,
        checkComment1: !!data.checkComment1,
        checkComment2: !!data.checkComment2,
        checkComment3: !!data.checkComment3,
        checkComment4: !!data.checkComment4,
        otherComments: data.otherComments,
        functionCounterSigner: data.functionCounterSigner,
        dateCompletionCounterSigner: data.dateCompletionCounterSigner,
        signatureCounterSigner: !!data.signatureCounterSigner
    }
}
