// <auto-generated />
using System;
using CVU.ERP.StorageService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CODWER.RERU.Storage.Console.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20220519135102_add-excell-file-type")]
    partial class addexcellfiletype
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CVU.ERP.StorageService.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BucketName")
                        .HasColumnType("text");

                    b.Property<string>("CreateById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UniqueFileName")
                        .HasColumnType("text");

                    b.Property<string>("UpdateById")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileType");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SpatialFocus.EntityFrameworkCore.Extensions.EnumWithNumberLookup<CVU.ERP.StorageService.Entities.FileTypeEnum>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FileTypeEnum");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "question"
                        },
                        new
                        {
                            Id = 2,
                            Name = "testtemplate"
                        },
                        new
                        {
                            Id = 3,
                            Name = "test"
                        },
                        new
                        {
                            Id = 4,
                            Name = "media"
                        },
                        new
                        {
                            Id = 5,
                            Name = "documents"
                        },
                        new
                        {
                            Id = 6,
                            Name = "identityfiles"
                        },
                        new
                        {
                            Id = 7,
                            Name = "photos"
                        },
                        new
                        {
                            Id = 8,
                            Name = "request"
                        },
                        new
                        {
                            Id = 9,
                            Name = "order"
                        },
                        new
                        {
                            Id = 10,
                            Name = "cim"
                        },
                        new
                        {
                            Id = 11,
                            Name = "procesfile"
                        });
                });

            modelBuilder.Entity("CVU.ERP.StorageService.Entities.File", b =>
                {
                    b.HasOne("SpatialFocus.EntityFrameworkCore.Extensions.EnumWithNumberLookup<CVU.ERP.StorageService.Entities.FileTypeEnum>", null)
                        .WithMany()
                        .HasForeignKey("FileType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
