# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Values.identity.name }}
# spec:
#   selector:
#     matchLabels:
#       app: {{ .Values.identity.name }}
#   replicas: {{ .Values.identity.replicas }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Values.identity.name }}
#     spec:
#       imagePullSecrets:
#       - name: {{ .Values.imagePullSecret.name }}
#       containers:
#       - name: {{ .Values.identity.name }}
#         image: {{ .Values.identity.image.repository }}:{{ .Values.tag }}
#         imagePullPolicy: Always
#         env:
#         - name: ConnectionStrings__Default
#           value: {{ .Values.identity.database.connection_string }}   
#         - name: TZ
#           value: {{ .Values.timeZone }}        
#         {{- if .Values.dotnet_microservice.deployment.env }}
# {{ toYaml .Values.dotnet_microservice.deployment.env | indent 8 }}
#         {{- end }}          
#         ports:
#         - containerPort: {{ .Values.microservice.port }}
#         livenessProbe:
#           httpGet:
#             path: {{ .Values.dotnet_microservice.deployment.liveness.livenessProbe }}
#             port: {{ .Values.microservice.port }}
#           initialDelaySeconds: {{ .Values.microservice.deployment.liveness.initialDelaySeconds }}
#           periodSeconds: {{ .Values.microservice.deployment.liveness.periodSeconds }}
#           timeoutSeconds: {{ .Values.microservice.deployment.liveness.timeoutSeconds }}

#         readinessProbe:
#           httpGet:
#             path: {{ .Values.dotnet_microservice.deployment.liveness.livenessProbe }}
#             port: {{ .Values.microservice.port }}
#           initialDelaySeconds: {{ .Values.microservice.deployment.readiness.initialDelaySeconds }}
#           periodSeconds: {{ .Values.microservice.deployment.readiness.periodSeconds }}
#           timeoutSeconds: {{ .Values.microservice.deployment.readiness.timeoutSeconds }}
