FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
RUN apt-get update && apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/*
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
ARG BUILD_CONFIGURATION=Production

WORKDIR /src
COPY . .
WORKDIR "/src/src/Microservices/CODWER.RERU.Core/CODWER.RERU.Core.API"
RUN dotnet restore --configfile Nuget.Config
RUN dotnet publish --configuration $BUILD_CONFIGURATION --output /publish

FROM base AS final
WORKDIR /app

RUN addgroup --gid 1000 app && adduser --uid 1000 app --ingroup app
USER 1000

RUN chmod 755 /app/Rotativa/Linux/wkhtmltopdf
COPY --chown=1000 --from=build /publish .
ENTRYPOINT ["dotnet", "CODWER.RERU.Core.API.dll"]