FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
RUN apt-get update && apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/*
WORKDIR /app
# Any ports can be exposed by setting env ASPNETCORE_URLS, eg.
# ENV ASPNETCORE_URLS http://*:8080
#USER 1001

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
ARG BUILD_CONFIGURATION=Production

WORKDIR /src
COPY . .
WORKDIR "/src/src/Microservices/CODWER.RERU.Gateway/CODWER.RERU.Gateway.Public/"
RUN dotnet restore --configfile Nuget.Config
RUN dotnet publish --configuration $BUILD_CONFIGURATION --output /publish

FROM base AS final
WORKDIR /app

RUN addgroup --gid 1000 app && adduser --uid 1000 app --ingroup app
USER 1000

COPY --chown=1000 --from=build /publish .

ENTRYPOINT ["dotnet", "CODWER.RERU.Gateway.Public.dll"]