FROM node:12.18.3-alpine as npm
WORKDIR /src
COPY . .
WORKDIR "/src/src/Front-End/reru/"

RUN npm install 
RUN npm run build erp-shared 
RUN npm link "./dist/erp-shared" 
RUN npm run build evaluation360 -- --prod --baseHref=/reru-evaluation360/

FROM nginxinc/nginx-unprivileged
COPY ./docker-files/docker-settings/nginx/nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html

COPY --from=npm /src/src/Front-End/reru/dist/evaluation360/ ./
