export enum DocumentKeyEnum {
    TodayDateKey = 1,
    NameKey = 2,
    LastNameKey = 3, 
    FatherNameKey = 4,
    IdnpKey = 5,
    BulletinSeriesKey = 6,
    BulletinRelaseByKey = 7,
    BulletinRelaseDayKey = 8,
    BirthdayKey = 9,
    WorkPlaceKey = 10,
    EmploymentDateKey = 11,
    WorkHoursKey = 12,
    SalaryKey = 13, 
    SexTypeKey = 14,
    RoleKey = 15,
    DissmisalDateKey = 16,
    InternshipDaysKey = 17,
    AddressKey = 18,
    CompanyKey = 19,
    CompanyPostCodeKey = 20,
    CompanyCityKey = 21,
    CompanyStreetKey = 22,
    CompanyIdnoKey = 23,
    DirectorNameKey =24,
    DirectorLastName = 25,
    MinisterSrlKey = 26
}